version: '3'

services:
    database:
        image: postgres:13-alpine
        environment:
            POSTGRES_USER: db_user
            POSTGRES_PASSWORD: db_password
            POSTGRES_DB: news_reader
        ports: 
            - "5432:5432"